### ISSUE TITLE
Last known value is not displayed when time range from grafana does not include the data point when it was created, giving wrong impression

### ISSUE THREAD

**Issue by kkmeghan** [grafana/iot-sitewise-datasource#138] opened 2022-08-25 07:31 UTC
![image](https://user-images.githubusercontent.com/36524874/186602744-5f8f7698-73dc-4c0a-90b2-0ca6857d4cb8.png)

The issue is being faced by many customers in Indiana Mfg Industries. The diagram is self explanatory with two examples.

**Comment by taleena** [comment] 2022-09-09 19:59
Hello @kkmeghan: This looks like a potential bug report. Would you be able to provide the below information to help us better troubleshoot? 


By providing as much info as possible you help us understand the issue, reproduce it and resolve it for you quicker. Therefore, take a couple of extra minutes to make sure you have provided all info needed.

PROTIP: record your screen and attach it as a gif to showcase the issue.

- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:



**Screenshots**



**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by kkmeghan** [comment] 2022-09-16 03:25
![Problem1](https://user-images.githubusercontent.com/36524874/190549780-d56c8f32-895d-4382-9304-bea3263dd53e.gif)


What happened:

Data not displayed , please see gif file

What you expected to happen:

Data should be displayed

How to reproduce it (as minimally and precisely as possible):

See gif file for a work flow. Data is created on sitewise using MQTT protocal and if the query window does not have data points it is not displayed.

Screenshots

Included 

Anything else we need to know?:

Environment:

Grafana version: 8.2.5
Plugin version: 1.3.0
OS Grafana is installed on: Linux
User OS & Browser: Windows and any browser (example chrome)
Others: Issue is already discussed with aws team in length in different meetings. Issue is related to the MQTT protocal and how the data is stored versus how it needs to be visualized

**Comment by toddtreece** [comment] 2022-09-24 00:26
`v1.4.0` was just released with a `Last Observation` toggle in the query editor, which will fall back to the last known value if no data is available in the current time range.

<img width="229" alt="image" src="https://user-images.githubusercontent.com/360020/192071973-f7a393ff-ee98-47fd-8f01-49d58c9180d7.png">

**Comment by kkmeghan** [comment] 2022-09-25 01:31
@toddtreece This will work only when atlease one data point is available in the time range selected. Please look into the above screen shot for two below time ranges

1/ 15.22.02 to 15.22.04, there is no data point stored in the back end.
2/ 15.22.13 to 15.32.11,there is no data point stored in the back end.

**Comment by toddtreece** [comment] 2022-09-26 12:37
> This will work only when atlease one data point is available in the time range selected

@kkmeghan Sorry, I'm not following what you mean here. The toggle enables a feature that will query for the last known point before the selected time range if the current time range is empty. Could you record a screen capture of the 1.4.0 release with the Last Observation toggle enabled so I could see how that differs from what you were expecting?

**Comment by kkmeghan** [comment] 2022-09-27 04:12
@toddtreece @taleena 

Please find the link to explore the problem. The below link has sitewise link under 'MeghaAI Features' panel.

https://d33leu70kunhgx.cloudfront.net/d/eSdByEGVk/meghaai-home?orgId=1

Alternatively following link will take you to that particular sitewise dashboard directly.

https://d33leu70kunhgx.cloudfront.net/d/hbfewPnVk/sitewise?orgId=1

This dashboard has two panels , one for historical data and one for aggregated data from sitewise.  Please follow the picture posted  in the beginning with this issue, this picture reflects how the data is populated into the sitewise. DARK blue cell reflect that the data is populated for that time instance and cyan cell reflect the data should be taken from the last known good value.

Please make a note last observation is selected for these two panels.

1/ Time range selected is 
from 2022-07-01 15:22:02  To 2022-07-01 15:22:04 , this case works as it fetches two points each with value 220 and Straight line can be seen.

2/ Time range selected is 

from 2022-07-01 15:22:02  To 2022-07-01 15:22:08, this case does not work as it only brings '221' in the panel. What should happen is that this query should bring

220(15:22:02), 221(15:22:05), 221(15:22:08)

3/ Please explore different testing cases similarly

will be happy to help in generating and testing new cases

**Comment by kkmeghan** [comment] 2022-10-07 04:18
@toddtreece  Hope the above is clear. Please let me know if help needed from our end.

**Comment by toddtreece** [comment] 2022-10-07 20:46
@taleena i think this is similar to #139 and also needs feedback from the AWS SiteWise team

**Comment by taleena** [comment] 2022-11-02 02:07
There are more details from discussions logged in #139, closing this as it will be handled in that issue.

**Closed by taleena** 2022-11-02 02:07 UTC
Labels: needs-more-info
