### ISSUE TITLE
failed to fetch query data: no aggregation values found for query

### ISSUE THREAD

**Issue by kkmeghan** [grafana/iot-sitewise-datasource#139] opened 2022-08-25 07:36 UTC
The error is displayed when you query for time range from grafana when no aggregation value is found for that time . The error is confusing for end users , many customers in Indiana Mfg Industries are getting confused what is happening.

![image](https://user-images.githubusercontent.com/36524874/186603999-557bc884-f902-4c01-8523-c8b9dd523919.png)

**Comment by taleena** [comment] 2022-09-09 19:58
Hello @kkmeghan: This looks like a potential bug report. Would you be able to provide the below information to help us better troubleshoot? 


By providing as much info as possible you help us understand the issue, reproduce it and resolve it for you quicker. Therefore, take a couple of extra minutes to make sure you have provided all info needed.

PROTIP: record your screen and attach it as a gif to showcase the issue.

- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:



**Screenshots**



**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by kkmeghan** [comment] 2022-09-16 03:27
![Problem2](https://user-images.githubusercontent.com/36524874/190550533-4b2e6d6f-fc60-4e66-9bbb-945e5b1d5298.gif)



What happened:

Data not displayed and error comes, please see gif file

What you expected to happen:

Data should be displayed

How to reproduce it (as minimally and precisely as possible):

See gif file for a work flow. Data is created on sitewise using MQTT protocal and if the query window does not have data points it is not displayed.

Screenshots

Included 

Anything else we need to know?:

Environment:

Grafana version: 8.2.5
Plugin version: 1.3.0
OS Grafana is installed on: Linux

User OS & Browser: Windows and any browser (example chrome)
Others: Issue is already discussed with aws team in length in different meetings. Issue is related to the MQTT protocol and how the data is stored versus how it needs to be visualized

**Comment by toddtreece** [comment] 2022-09-24 00:22
@kkmeghan it seems as if this error is coming from the AWS API and not the data source. Grafana will not be able to visualize data unless something is returned from the AWS API for the queried time range.

> Issue is already discussed with aws team in length in different meetings.

Could you provide any additional details about those conversations?

**Comment by kkmeghan** [comment] 2022-09-25 01:36
@toddtreece  Please let me know what additional information is missing and needed. Grafana has time range for the data to be queried and in back end if that time range does not have data points ( from MQTT behaviour), this will results in error.

**Comment by taleena** [comment] 2022-09-26 15:17
@kkmeghan

**Comment by taleena** [comment] 2022-09-29 22:41
Got it. Because we're taking data that comes from the interpolated API, we're expecting it to provide us with data points (either real or predicted). Maybe something to do with aggregating not taking into account predictions? I'm checking in with AWS regarding the API, since we don't have the context from those conversations.

**Comment by kkmeghan** [comment] 2022-09-30 04:15
@taleena  The whole idea from end user's perspective is to get aggregated values for time range selected from grafana UI. It does not matter for end users how the data points are stored in the sitewise but how to interpret these data points is more important. Just because the data points are not stored in the time range does not imply that previous values are not valid for that time range and that is the heart of the whole matter here.

**Comment by ryantxu** [comment] 2022-09-30 05:57
How does this work in the iot-sitewise portal?  I am trying to understand if this is an issue with the query, data, or an enhancement request to support something the sitewise APIs do not support directly.

**Comment by ryantxu** [comment] 2022-09-30 06:03
@kkmeghan -- I think I understand what you are asking for, I am just not sure how to best solve it with a sitewise query.

IIUC, you might need three queries to "cover" the selected time range:
1. The last point before the time range
2. The data within the time range
3. The next point after the time range

Then all three results could be collapsed into a single series.   Some other datasources can do this natively (eg influx+flux), but not sure how to best solve this in sitewise.

**Comment by kkmeghan** [comment] 2022-09-30 11:06
@ryantxu Please let me know how I can help here. If there is a meeting coordination needed with sitewise team, let us do it.The data storage is not same as what end users interpret the data, whether visualization or any other computation.

**Comment by taleena** [comment] 2022-10-06 20:28
@kkmeghan does @ryantxu comment above accurately represent what you are looking for? If so, this is a new feature request. I've contacted the SiteWise PM to see how best to handle, there might be an API that does this we don't know about, or it could be something we need to implement either at the plugin or at a more general level.

**Comment by kkmeghan** [comment] 2022-10-07 03:35
@ryantxu @taleena  I see two different cases when end users perspective in the context of the data.

1/  Continuous streaming data , but stored whenever there is change in the value.

End users will like to have the aggregated data which makes sense even if there are no data points in the time series database at back end. Let us take above example for 'voltage', what is average voltage between 18.00 to 19.00 on 07/01/2022 ? Though there are no data points in the database , because of storage mechanism, still the average voltage is valid value to ask for .

2/ Discrete data values, which makes sense only for the time they are stored.

Let us , say 'GoodCount' of parts produced by a machine at particular time. This does not need to be carry forward as this represent discrete values.

What I think is an 'option' to use previous known values or not while doing aggregations.

**Comment by diehbria** [comment] 2022-10-18 17:19
> @kkmeghan does @ryantxu comment above accurately represent what you are looking for? If so, this is a new feature request. I've contacted the SiteWise PM to see how best to handle, there might be an API that does this we don't know about, or it could be something we need to implement either at the plugin or at a more general level.

You can make queries to get the last data point before a certain point in time, either after or before, by utilizing https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_GetAssetPropertyValueHistory.html without any additional features. By setting `maxResults` to 1, and setting the `timeOrdering` in the direction you wish to search, we get the desired behavior

For example, to search for the most recent data point at or before 2000, we could use:
`maxResults`: 1
`startDate`: new Date(0, 0, 0, 0) (any super early date that will be before all data points
`endDate`: new Date(2000, 0, 0)
`timeOrdering`: "DESCENDING"

Potentially searching through a large time interval with no data present is not an issue with SiteWise, so this will also give good performance

**Comment by kkmeghan** [comment] 2022-10-19 01:37
@diehbria I responded earlier. Repeating same again here

There are two different cases from end users' perspective in the context of the data. We need associated data points and visualization with below cases in minds. This may boil down to what @ryantxu  mentioned at least for the case 1 and not for case2. The context of the data have to be taken into consideration. Understand we have the APIs for data points, here we need generic solution for sitewise-grafana plugin.

1/ Continuous streaming data, but stored whenever there is change in the value.

End users will like to have the aggregated data which makes sense even if there are no data points in the time series database at back end. Let us take above example for 'voltage', what is average voltage between 18.00 to 19.00 on 07/01/2022 ? Though there are no data points in the database , because of storage mechanism, still the average voltage is valid value to ask for .

2/ Discrete data values, which makes sense only for the time they are stored.

Let us , say 'GoodCount' of parts produced by a machine at particular time. This does not need to be carry forward as this represent discrete values.

What I think is an 'option' to use previous known values or not while doing aggregations.

**Comment by diehbria** [comment] 2022-10-21 19:53
@kkmeghan my apologies I misunderstood the question.

I believe I understand the problem, sometimes you need data beyond the actively viewed time frame (such as a line chart)

![Screen Shot 2022-10-21 at 12 22 37 PM](https://user-images.githubusercontent.com/77755322/197277761-d11c74fe-7afe-452e-848b-6e23c94afd03.png)

but for other widgets, you want to ability to configure whether it has this behavior of looking beyond the viewed time range - depending on the exact use case the user (you) has.

**Comment by kkmeghan** [comment] 2022-10-22 04:59
@diehbria  , The correct interpretation is below , there is grafana option to selection how the points should be connected,  however the points are only connected when there are points fetched inside grafana. For example, in this case if the last point was not there, we will never get the complete graph. Please let me know if we need to connect on ZOOM


![image](https://user-images.githubusercontent.com/36524874/197320644-f243ec22-51b9-4568-9ac0-8a33301bb650.png)

**Comment by taleena** [comment] 2022-11-02 02:05
We've met and talked through this and have a path forward. As a super quick summary, we will not mix raw data with aggregated data. For now, there is a dependency within grafana/grafana, https://github.com/grafana/grafana/pull/57798, recently merged.

**Comment by kkmeghan** [comment] 2022-11-02 02:47
@taleena  Thank you. Not sure If I understood the summary. Is the problem solved ? If yes, which version we can test it ?

**Comment by taleena** [comment] 2022-11-02 16:26
No, this is not yet solved, but we spoke with @diehbria and we have an understood way on how to approach the fix. You will see a PR when we're closer to releasing a fix.

**Comment by kkmeghan** [comment] 2022-11-15 09:13
@taleena  I am also leaving one more test case. Please see the problem at the following link

https://d33leu70kunhgx.cloudfront.net/d/hbfewPnVk/sitewise?orgId=1&from=1656688920000&to=1658394048000

There are two time series graphs, one with raw values ( Getpropertyvaluehistory) and other aggregated values with (GetProperty Value Aggregates) with 'Average' option and '1m' resolution. 

We can see the graph for Getpropertyvaluehistory but GetProperty Value Aggregates has stopped in between for the same 'property'. Ideally the graph for GetProperty Value Aggregates should have continued and calculated the average at different intervals.

Customer is asking fix and reason behind the same.

**Comment by taleena** [comment] 2022-11-29 20:05
This also has a dependency that is being worked on here: https://github.com/grafana/grafana/pull/57798

**Comment by toddtreece** [comment] 2022-11-29 21:36
#147 includes a change that should cover the next & last values outside of the time range, but it requires the changes in https://github.com/grafana/grafana/pull/59444, which won't be available until 9.4.0 (or possibly 9.3.1 depending on if it's backported)

**Comment by toddtreece** [comment] 2022-11-29 21:52
> There are two time series graphs, one with raw values ( Getpropertyvaluehistory) and other aggregated values with (GetProperty Value Aggregates) with 'Average' option and '1m' resolution.

@kkmeghan from what i can tell the data is not being returned from the sitewise API. the second page returns an empty result without a next token. would it be possible to test this same query with the sitewise API outside of grafana?

**Comment by kkmeghan** [comment] 2022-11-30 05:05
@taleena  Thanks for response. When do we expect availability of 9.4.0 ? Do we have some tentative timeline for same ?

**Comment by kkmeghan** [comment] 2022-11-30 05:06
@taleena we get it tested beyond grafana.

**Closed** 2022-11-30 19:35 UTC
Labels: enhancement, prio/high
