### ISSUE TITLE
Plugin error when querying asset property aggregates

### ISSUE THREAD

**Issue by mustafain117** [grafana/iot-sitewise-datasource#195] opened 2023-06-01 19:35 UTC
**What happened**:
Internal Server Error when using IoT SiteWise datasource with the 'Get property value aggregates' query type:
```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "resolution": "AUTO",
          "aggregates": [
            "AVERAGE"
          ],
          "timeOrdering": "ASCENDING",
          "datasource": {
            "type": "grafana-iot-sitewise-datasource",
            "uid": "lmvNtQwVk"
          },
          "refId": "A",
          "maxPageAggregations": 1,
          "queryType": "PropertyAggregate",
          "assetIds": [
            "bf774c69-5503-4eff-a032-89028106f1a0"
          ],
          "propertyId": "527a8c35-3e41-4dc2-a011-c7f9b04d447f",
          "responseFormat": "table",
          "lastObservation": false,
          "propertyAlias": "",
          "region": "",
          "datasourceId": 3,
          "intervalMs": 10000,
          "maxDataPoints": 884
        }
      ],
      "range": {
        "from": "2023-06-01T16:22:07.843Z",
        "to": "2023-06-01T19:22:07.843Z",
        "raw": {
          "from": "now-3h",
          "to": "now"
        }
      },
      "from": "1685636527843",
      "to": "1685647327843"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "An error occurred within the plugin",
    "messageId": "plugin.downstreamError",
    "statusCode": 500,
    "traceID": ""
  }
}
```
Using a smaller time duration fixes the error.
**What you expected to happen**:
Expect the query to work or display a more descriptive error if something is wrong with the query itself.
Running the same query against iot sitewise API using CLI provides a descriptive message:
```
aws iotsitewise get-asset-property-aggregates \
--asset-id bf774c69-5503-4eff-a032-89028106f1a0 \
--property-id 527a8c35-3e41-4dc2-a011-c7f9b04d447f \
--aggregate-types AVERAGE \
--resolution 1m \
--region us-west-2 \
--start-date 1685636527843 \
--end-date 1685647327843
```
Returns:
```
signed integer is greater than maximum
```
Expect similar message to be displayed in Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

Query is provided above. IoT Sitewise resources were set up using the getting started demo: https://docs.aws.amazon.com/iot-sitewise/latest/userguide/getting-started-demo.html

**Screenshots**
<img width="905" alt="image" src="https://github.com/grafana/iot-sitewise-datasource/assets/38258861/9020c697-4f5b-4903-a33c-b6f5481775b7">

**Anything else we need to know?**:

**Environment**: Amazon Managed Grafana
- Grafana version: 9.4.7
- Plugin version: 1.7.0
- OS Grafana is installed on: N/A
- User OS & Browser: FireFox
- Others:

**Comment by sarahzinger** [comment] 2023-06-02 18:24
Hi @mustafain117 I think this might be a duplicate of https://github.com/grafana/iot-sitewise-datasource/issues/182, does changing the resolution/timescale help resolve this for you?

**Comment by mustafain117** [comment] 2023-06-02 18:51
Hi @sarahzinger, reducing the time range for the query or using a higher resolution resolves the issue so might be related.

**Comment by sarahzinger** [comment] 2023-06-02 19:00
Cool, I will look into seeing if we can reprioritize this issue to get eyes on it a bit faster. Thanks for your patience and reporting!

**Comment by egheie** [comment] 2023-06-06 06:42
Hi! This seem to be similar to what we experience and reported in #160 as well, which is currently in progress.

**Closed** 2023-07-13 15:39 UTC
Labels: type/bug, datasource/Sitewise

**Comment by kevinwcyu** [comment] 2023-07-13 15:40
Hi @mustafain117, this should be fixed now. Could you please try the latest version of the plugin?
