### ISSUE TITLE
Scope: Issue querying data by `propertyAlias` when the property is associated with an asset

### ISSUE THREAD

**Issue by diehbria** [grafana/iot-sitewise-datasource#169] opened 2023-03-07 20:24 UTC
**What happened**:
Cannot construct query based on `propertyAlias` for a property which has a `propertyAlias` but is also associated with a SiteWise asset.

**What you expected to happen**:
Able to construct queries based on `propertyAlias` for any properties which contain a `propertyAlias` (which both modeled and unmodeled data supports)

**Comment by iwysiu** [comment] 2023-03-09 19:45
Hi @diehbria !

Thanks for reporting this issue! I think I've reproduced it, but I would appreciate if you could reply with an example of a query with this issue and what error you get returned to be sure.

**Comment by iwysiu** [comment] 2023-03-09 20:19
Ah, while investigating the code, it seems like when the plugin was written the design decision was made not to support propertyAlias targets for property value queries: https://github.com/grafana/iot-sitewise-datasource/blob/fa1bd02b12b7d37bcb8d1c58b31ec4f93ef33cef/pkg/models/property.go#L11 However it also has been 2 years since then, so I'll put this in the backlog for us to look into adding.

**Comment by sarahzinger** [comment] 2023-04-03 13:27
This is marked as a bug for now, but might be more of a feature request. Let's take a look this sprint and see what it would involve to support this, might require creating this into it's own epic with design doc?

**Comment by diehbria** [comment] 2023-04-18 19:14
@iwysiu @sarahzinger 

Regarding this comment:

>  // NOTES: We have decided to not support propertyAlias targets, as there is no good way to go from propertyAlias -> assetId/propertyId. 

You can determine the assetId and propertyId associated with a property given an `propertyAlias` with the `DescribeTimeSeries` API.

You can learn more ahttps://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_DescribeTimeSeries.html

You will make a request `/timeseries/describe/?alias=$PROPERTY_ALIAS` and this will return a response that contains a `assetId` and `propertyId` field

**Closed** 2023-05-11 21:43 UTC
Labels: type/bug, prio/high, datasource/Sitewise, effort/large
